@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": ""
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false // root node is included
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "prak32.BankProducts"
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_103904626 { 
   	label=JavaProjects
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1230273184 { 
   	label=prak32
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   BankProducts1660034155[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(E)BankProducts</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   Credit: BankProducts [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   Currency: BankProducts [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   Deposit: BankProducts [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   DocumentsAndReceipts: BankProducts [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   PlasticCards: BankProducts [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   Promissory: BankProducts [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   numb: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ valueOf(name: String): BankProducts</TD></TR>
<TR><TD ALIGN="LEFT" >+ values(): BankProducts[]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#DCFBD5"
];

BankService1660034155[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)BankService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+   accountNumb: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   additService: AdditService [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   closingDate: Date [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   openingDate: Date [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >+   productType: BankProducts [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
BankService1660034155 -> BankProducts1660034155[label="productType
[0..1]"];
    
}
@enduml